import os
import time
from github import Github

# Get env vars from GitHub Actions
api_key = os.getenv("MINIMAX_API_KEY")
gh_token = os.getenv("GITHUB_TOKEN")
comment_body = os.getenv("COMMENT_BODY")
issue_number = int(os.getenv("ISSUE_NUMBER"))
repo_name = os.getenv("REPO_NAME")

def call_minimax(prompt, api_key):
    """
    Hit the MiniMax API. 
    Returns a mock response for now to test the logic.
    """
    # In production, we'll use requests.post here.
    # Simulation: Agent thinks, but realizes it needs more info
    if "setup" in prompt.lower():
        return "<think>User wants to setup a server, but I don't know the language.</think> I'm ready to help, but should I use Node.js or Python for this server?"
    
    # Simulation: Agent thinks and provides a fix
    return "<think>Fixing the math logic in calc.py.</think> file:calc.py\ncontent:def add(a, b):\n    return a + b"

def create_pull_request(repo, branch_name, file_path, new_content):
    """
    Handle the Git heavy lifting.
    """
    main = repo.get_branch("main")
    repo.create_git_ref(ref=f"refs/heads/{branch_name}", sha=main.commit.sha)
    
    try:
        # Update if exists
        contents = repo.get_contents(file_path, ref="main")
        repo.update_file(contents.path, "AI bug fix", new_content, contents.sha, branch=branch_name)
    except:
        # Create if new
        repo.create_file(file_path, "AI feature creation", new_content, branch=branch_name)
    
    return repo.create_pull(
        title=f"AI Fix for Issue #{issue_number}",
        body="Automated fix generated by MiniMax M2.1",
        head=branch_name,
        base="main"
    )

def parse_and_execute(repo, issue, raw_response):
    """
    Extract thinking process and decide between PR or Question.
    """
    # 1. Grab the <think> tags for transparency
    if "<think>" in raw_response:
        parts = raw_response.split("<think>")
        inner_parts = parts[1].split("</think>")
        thought = inner_parts[0].strip()
        actual_content = inner_parts[1].strip()
        
        issue.create_comment(f"🧠 **Agent Thinking:**\n> {thought}")
    else:
        actual_content = raw_response.strip()

    # 2. Check if we are creating a file or just asking a question
    if "file:" in actual_content and "content:" in actual_content:
        try:
            # Simple parsing for the file data
            file_data = actual_content.split("\ncontent:")
            file_path = file_data[0].replace("file:", "").strip()
            new_code = file_data[1].strip()
            
            branch_name = f"ai-agent-fix-{issue_number}-{int(time.time())}"
            pr = create_pull_request(repo, branch_name, file_path, new_code)
            
            issue.create_comment(f"✅ I've opened a Pull Request with the changes: {pr.html_url}")
        except Exception as e:
            issue.create_comment(f"❌ Tried to create a PR but failed: {str(e)}")
    else:
        # If no file tags found, it's a question for the dev
        issue.create_comment(f"❓ **Agent Question:**\n\n{actual_content}")

def run_agent():
    # Setup GH connection
    g = Github(gh_token)
    repo = g.get_repo(repo_name)
    issue = repo.get_issue(number=issue_number)

    # Check for API key
    if not api_key or api_key == "waiting_for_key":
        issue.create_comment("⚠️ Simulation Mode: Ready for MiniMax API Key.")
        return

    # Trigger the AI loop
    issue.create_comment("🤖 Agent is analyzing the request...")
    ai_output = call_minimax(comment_body, api_key)
    parse_and_execute(repo, issue, ai_output)

if __name__ == "__main__":
    run_agent()
