name: MiniMax AI Agent
on:
  issue_comment:
    types: [created]

jobs:
  run-agent:
    if: contains(github.event.comment.body, '@agent')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests PyGithub

      - name: Run Agent Logic
        env:
          MINIMAX_API_KEY: ${{ secrets.MINIMAX_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          REPO_NAME: ${{ github.repository }}
        run: python agent_logic.py
